FROM python:3.7.3

copy /app /etc/usr/src/app
copy requirements.txt /etc/usr/src/requirements.txt

# Install dependencies
RUN pip install -r /etc/usr/src/requirements.txt && rm /etc/usr/src/requirements.txt

workdir /etc/usr/src/app

# Run python script when the container launches
ENTRYPOINT ["python"]
CMD ["measurements_manager_api.py"]